[log]
    level = "INFO"

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false

#[api]
  #dashboard = true
  #insecure = true

[certificatesResolvers.main.acme]
    email = "daniel.barreto@merantix.com"
    storage = "acme.json"
    [certificatesResolvers.main.acme.httpChallenge]
        entryPoint = "http"
